version: "3"
services:
  selenoid:
    image: aerokube/selenoid:1.11.0
    network_mode: bridge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/:/etc/selenoid/"
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.10
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

volumes:
  video:
    driver: local
